# Generated by Django 5.0.4 on 2024-04-05 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("sobre_nome", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=70,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Email inválido."
                            )
                        ],
                    ),
                ),
                ("data_nascimento", models.DateTimeField()),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
