# Generated by Django 5.0.4 on 2024-04-05 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="aluno",
            table="aluno",
        ),
    ]
